[project]
name = "mdft"
version = "0.1.3"
readme = "README.md"
requires-python = ">=3.9"
description = "Package for generating file trees in Markdown"
authors = [
  { name="Rafael Copstein", email="rcopstein@gmail.com" },
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
dependencies = [
    "pathspec>=0.12.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/rcopstein/mdft"
Issues = "https://github.com/rcopstein/mdft/issues"
